// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"team-manager/ent/direction"
	"team-manager/ent/predicate"
	"team-manager/ent/schedule"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DirectionQuery is the builder for querying Direction entities.
type DirectionQuery struct {
	config
	ctx                    *QueryContext
	order                  []direction.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Direction
	withDirectionSchedules *ScheduleQuery
	modifiers              []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DirectionQuery builder.
func (dq *DirectionQuery) Where(ps ...predicate.Direction) *DirectionQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DirectionQuery) Limit(limit int) *DirectionQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DirectionQuery) Offset(offset int) *DirectionQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DirectionQuery) Unique(unique bool) *DirectionQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DirectionQuery) Order(o ...direction.OrderOption) *DirectionQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryDirectionSchedules chains the current query on the "direction_schedules" edge.
func (dq *DirectionQuery) QueryDirectionSchedules() *ScheduleQuery {
	query := (&ScheduleClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(direction.Table, direction.FieldID, selector),
			sqlgraph.To(schedule.Table, schedule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, direction.DirectionSchedulesTable, direction.DirectionSchedulesColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Direction entity from the query.
// Returns a *NotFoundError when no Direction was found.
func (dq *DirectionQuery) First(ctx context.Context) (*Direction, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{direction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DirectionQuery) FirstX(ctx context.Context) *Direction {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Direction ID from the query.
// Returns a *NotFoundError when no Direction ID was found.
func (dq *DirectionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{direction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DirectionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Direction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Direction entity is found.
// Returns a *NotFoundError when no Direction entities are found.
func (dq *DirectionQuery) Only(ctx context.Context) (*Direction, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{direction.Label}
	default:
		return nil, &NotSingularError{direction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DirectionQuery) OnlyX(ctx context.Context) *Direction {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Direction ID in the query.
// Returns a *NotSingularError when more than one Direction ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DirectionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{direction.Label}
	default:
		err = &NotSingularError{direction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DirectionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Directions.
func (dq *DirectionQuery) All(ctx context.Context) ([]*Direction, error) {
	ctx = setContextOp(ctx, dq.ctx, "All")
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Direction, *DirectionQuery]()
	return withInterceptors[[]*Direction](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DirectionQuery) AllX(ctx context.Context) []*Direction {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Direction IDs.
func (dq *DirectionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, "IDs")
	if err = dq.Select(direction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DirectionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DirectionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, "Count")
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DirectionQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DirectionQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DirectionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, "Exist")
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DirectionQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DirectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DirectionQuery) Clone() *DirectionQuery {
	if dq == nil {
		return nil
	}
	return &DirectionQuery{
		config:                 dq.config,
		ctx:                    dq.ctx.Clone(),
		order:                  append([]direction.OrderOption{}, dq.order...),
		inters:                 append([]Interceptor{}, dq.inters...),
		predicates:             append([]predicate.Direction{}, dq.predicates...),
		withDirectionSchedules: dq.withDirectionSchedules.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithDirectionSchedules tells the query-builder to eager-load the nodes that are connected to
// the "direction_schedules" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DirectionQuery) WithDirectionSchedules(opts ...func(*ScheduleQuery)) *DirectionQuery {
	query := (&ScheduleClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withDirectionSchedules = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartStationID int64 `json:"start_station_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Direction.Query().
//		GroupBy(direction.FieldStartStationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DirectionQuery) GroupBy(field string, fields ...string) *DirectionGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DirectionGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = direction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartStationID int64 `json:"start_station_id,omitempty"`
//	}
//
//	client.Direction.Query().
//		Select(direction.FieldStartStationID).
//		Scan(ctx, &v)
func (dq *DirectionQuery) Select(fields ...string) *DirectionSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DirectionSelect{DirectionQuery: dq}
	sbuild.label = direction.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DirectionSelect configured with the given aggregations.
func (dq *DirectionQuery) Aggregate(fns ...AggregateFunc) *DirectionSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DirectionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !direction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DirectionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Direction, error) {
	var (
		nodes       = []*Direction{}
		_spec       = dq.querySpec()
		loadedTypes = [1]bool{
			dq.withDirectionSchedules != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Direction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Direction{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(dq.modifiers) > 0 {
		_spec.Modifiers = dq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withDirectionSchedules; query != nil {
		if err := dq.loadDirectionSchedules(ctx, query, nodes,
			func(n *Direction) { n.Edges.DirectionSchedules = []*Schedule{} },
			func(n *Direction, e *Schedule) { n.Edges.DirectionSchedules = append(n.Edges.DirectionSchedules, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DirectionQuery) loadDirectionSchedules(ctx context.Context, query *ScheduleQuery, nodes []*Direction, init func(*Direction), assign func(*Direction, *Schedule)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Direction)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(schedule.FieldDirectionID)
	}
	query.Where(predicate.Schedule(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(direction.DirectionSchedulesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DirectionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "direction_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (dq *DirectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	if len(dq.modifiers) > 0 {
		_spec.Modifiers = dq.modifiers
	}
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DirectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(direction.Table, direction.Columns, sqlgraph.NewFieldSpec(direction.FieldID, field.TypeInt64))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, direction.FieldID)
		for i := range fields {
			if fields[i] != direction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DirectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(direction.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = direction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range dq.modifiers {
		m(selector)
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dq *DirectionQuery) Modify(modifiers ...func(s *sql.Selector)) *DirectionSelect {
	dq.modifiers = append(dq.modifiers, modifiers...)
	return dq.Select()
}

// DirectionGroupBy is the group-by builder for Direction entities.
type DirectionGroupBy struct {
	selector
	build *DirectionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DirectionGroupBy) Aggregate(fns ...AggregateFunc) *DirectionGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DirectionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, "GroupBy")
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectionQuery, *DirectionGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DirectionGroupBy) sqlScan(ctx context.Context, root *DirectionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DirectionSelect is the builder for selecting fields of Direction entities.
type DirectionSelect struct {
	*DirectionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DirectionSelect) Aggregate(fns ...AggregateFunc) *DirectionSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DirectionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, "Select")
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectionQuery, *DirectionSelect](ctx, ds.DirectionQuery, ds, ds.inters, v)
}

func (ds *DirectionSelect) sqlScan(ctx context.Context, root *DirectionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ds *DirectionSelect) Modify(modifiers ...func(s *sql.Selector)) *DirectionSelect {
	ds.modifiers = append(ds.modifiers, modifiers...)
	return ds
}
