// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Direction is the predicate function for direction builders.
type Direction func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// Station is the predicate function for station builders.
type Station func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
